name: ctf
services:
  # PostgreSQL
  # db:
  #   image: postgres:16
  #   environment:
  #     POSTGRES_USER: ctf
  #     POSTGRES_PASSWORD: password
  #     POSTGRES_DB: ctf
  #   ports:
  #     - 4224:5432
  #   volumes:
  #     - postgres-data:/var/lib/postgresql/data
  # MariaDB
  db:
    image: mariadb:11.5-rc
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: ctf
      MYSQL_USER: ctf
      MYSQL_PASSWORD: password
    ports:
      - 4224:3306
    volumes:
      - mariadb-data:/var/lib/mysql

  clamav:
    image: clamav/clamav:1.2
    ports:
      - 3310:3310
 
  # prometheus:
  #   image: prom/prometheus:v2.52.0
  #   ports:
  #     - 9090:9090
  #   volumes:
  #     - ./config/prometheus/prometheus.yaml:/etc/prometheus/prometheus.yml
  #     - prometheus-data:/prometheus
  # grafana:
  #   image: grafana/grafana:10.4.4
  #   ports:
  #     - 3000:3000
volumes:
  postgres-data:
  mariadb-data:
  # prometheus-data:
