spring:
  application:
    name: ctf
  datasource:
    url: jdbc:postgresql://localhost:5432/ctf
    username: ctf
    password: password
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    open-in-view: false
server:
  servlet:
    context-path: /api
security:
  jwt:
    secret: Rn4x02v8+G/CpX5IwNI4+Asc+UpBA8nmW0iB2hVCiJf+lPJZrkCVwaDcARssEl1mYkWb3xr77dSigp5LlM+VLg==
    expiration: 86400000
