spring:
  application:
    name: ctf
  datasource:
    url: jdbc:postgresql://localhost:5432/ctf
    username: ctf
    password: password
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    open-in-view: false
server:
  servlet:
    context-path: /api
token:
  signing:
    key: 413F4428472B4B6250655368566D5970337336763979244226452948404D6351
